### ISSUE TITLE
No key for conmed in patient profile

### ISSUE THREAD

**Issue by nikolas-burkoff** [insightsengineering/osprey#81]
From https://github.com/insightsengineering/coredev-tasks/issues/242

![image](https://user-images.githubusercontent.com/15201933/171371061-569df7e9-6e76-4ca4-943f-2a2b2db9ea03.png)

@kumamiao  is this deliberate?

**Comment by lcd2yyz** [comment]
I wouldn't call this "deliberate", but somewhat "inherent" for the type of data, so maybe not needed. 
Conmed (and AEs, as partially shown in the first panel) are type of occurrence data. So the line segment naturally signify the duration, with start and end dates marked by circle and square respectively.
The AE panel has a legend, most likely due to the fact that different events are associated with different toxicity grades, or varying degree of seriousness. Whereas, there are no categorical or differentiating factors of similar nature for conmeds.
